# For most projects, this workflow file will not need changing; you simply need
# to commit it to your repository.
#
# You may wish to alter this file to override the set of languages analyzed,
# or to provide custom queries or build logic.
#
# ******** NOTE ********
# We have attempted to detect the languages in your repository. Please check
# the `language` matrix defined below to confirm you have the correct set of
# supported CodeQL languages.
#
name: 'CodeAnalysis'

on:
    push:
        branches: [main, develop, hotfix]
    pull_request:
        # The branches below must be a subset of the branches above
        branches: [main, develop, hotfix]

jobs:
    analyzeAndTest:
        name: Analyze & Test
        runs-on: ubuntu-latest
        permissions:
            actions: read
            contents: read
            security-events: write

        strategy:
            fail-fast: false
            matrix:
                language: ['javascript']

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - uses: actions/setup-node@v3
              with:
                  node-version: 16
                  registry-url: https://registry.npmjs.org/

            - run: npm ci --ignore-scripts

            - run: npm run lint

            # Initializes the CodeQL tools for scanning.
            - name: Initialize CodeQL
              uses: github/codeql-action/init@v2
              with:
                  languages: ${{ matrix.language }}
            - name: Perform CodeQL Analysis
              uses: github/codeql-action/analyze@v2
              with:
                  category: '/language:${{matrix.language}}'

            # Assuming code passes, run tests
            - name: Run mcdev-tests
              run: npm run coverage
            - name: Generate NYC report
              run: |
                  npx nyc report \
                    --reporter json-summary \
                    --exclude-after-remap false
            - name: Report NYC coverage
              uses: sidx1024/report-nyc-coverage-github-action@v1.2.6
              with:
                  # Path to coverage file generated by "nyc report".
                  coverage_file: 'coverage/coverage-summary.json'
