on: [pull_request]

name: Test coverage report
jobs:
    hello_world_job:
        runs-on: ubuntu-latest
        name: Test and report
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  ref: ${{ github.event.pull_request.head.sha }}
                  fetch-depth: 1000

            - uses: actions/setup-node@v3
              with:
                  node-version: 16

            - name: Run tests
              run: |
                  npm ci --ignore-scripts
                  npm i svelte-to-html@1.0.9
                  npm run coverage
                  npx nyc report --reporter json-summary --exclude-after-remap false

            - name: Upload coverage artifact
              uses: actions/upload-artifact@v3
              with:
                  name: test-coverage-output
                  path: coverage

            - name: Download coverage artifact
              uses: actions/download-artifact@v3
              with:
                  path: artifacts

            - name: Get Run ID
              id: get_run_id
              run: |
                  echo "::set-output name=run_id::$(\
                    gh run list \
                      --workflow "${{ github.event.pull_request.base.ref == 'main' && 'coverage-default-branch.yml' || 'coverage-main.yml' }}" \
                      --json conclusion,headSha,status,databaseId \
                      --jq ".[] | select( .conclusion == \"success\" and .headSha == \"${{github.event.pull_request.base.sha}}\") | .databaseId" \
                  )"
              env:
                  GITHUB_TOKEN: ${{ github.token }}

            - name: Download artifact
              uses: dawidd6/action-download-artifact@v2
              continue-on-error: true
              with:
                  workflow: ${{ github.event.pull_request.base.ref == 'main' && 'coverage-default-branch.yml' || 'coverage-main.yml' }}
                  run_id: ${{steps.get_run_id.outputs.run_id}}
                  name: 'test-coverage-output'
                  path: base-artifacts
                  search_artifacts: true

            - name: Check file existence
              id: check_files
              uses: andstor/file-existence-action@v2
              with:
                  files: 'base-artifacts/coverage-summary.json'

            - name: Prepare for Report Coverage
              run: |
                  npm i svelte-to-html@1.0.9
                  git fetch origin ${{ github.event.pull_request.base.ref }} --depth=1000

            - name: Report coverage
              uses: sidx1024/report-nyc-coverage-github-action@v1.2.6
              id: report
              with:
                  coverage_file: 'artifacts/test-coverage-output/coverage-summary.json'
                  base_coverage_file: ${{steps.check_files.outputs.files_exists == 'true' && 'base-artifacts/coverage-summary.json' || ''}}
                  comment_template_file: '.coverage-comment-template.svelte'
